# Generated by Django 2.0.5 on 2018-06-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Authenticator',
            field=models.CharField(max_length=500, verbose_name='用户凭证'),
        ),
    ]
