# Generated by Django 2.0.3 on 2018-06-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0003_auto_20180619_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='getdata',
            name='floor',
            field=models.CharField(max_length=20, null=True, verbose_name='楼层'),
        ),
    ]
