# Generated by Django 2.0.1 on 2018-06-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0004_getdata_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day_data',
            options={'verbose_name': '烟感日志', 'verbose_name_plural': '烟感日志'},
        ),
        migrations.AlterModelOptions(
            name='focus_data',
            options={'verbose_name': '烟感实时报警', 'verbose_name_plural': '烟感实时报警'},
        ),
        migrations.AlterModelOptions(
            name='month_data',
            options={'verbose_name': '烟感月志', 'verbose_name_plural': '烟感月志'},
        ),
        migrations.AlterModelOptions(
            name='week_data',
            options={'verbose_name': '烟感周志', 'verbose_name_plural': '烟感周志'},
        ),
    ]
