# Generated by Django 2.0.1 on 2018-06-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0005_auto_20180626_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Getdata_v2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=255, verbose_name='设备类型')),
                ('sensor_id', models.CharField(max_length=255, verbose_name='设备ID')),
                ('sensor_name', models.CharField(max_length=255, verbose_name='设备名字')),
                ('point_type', models.IntegerField(max_length=255, verbose_name='关联事件类型')),
                ('point_type_name', models.CharField(max_length=255, verbose_name='关联事件类型名字')),
                ('point_id', models.IntegerField(max_length=255, verbose_name='关联事件ID')),
                ('point_name', models.CharField(max_length=255, verbose_name='关联事件名字')),
                ('address', models.CharField(max_length=255, verbose_name='安装地址')),
                ('photo_url', models.CharField(max_length=255, verbose_name='现场照片URL')),
                ('build_time', models.CharField(max_length=255, verbose_name='安装时间')),
                ('lng', models.CharField(max_length=255, verbose_name='经度')),
                ('lat', models.CharField(max_length=255, verbose_name='纬度')),
                ('floor', models.IntegerField(max_length=255, verbose_name='安装楼层')),
                ('region_id', models.CharField(max_length=255, verbose_name='所属街道ID')),
                ('region_name', models.CharField(max_length=255, verbose_name='所属街道名称')),
                ('piece_id', models.CharField(max_length=255, verbose_name='所属片区ID')),
                ('piece_name', models.CharField(max_length=255, verbose_name='所属片区名字')),
                ('committee_id', models.CharField(max_length=255, verbose_name='所属居委ID')),
                ('committee_name', models.CharField(max_length=255, verbose_name='所属居委名字')),
                ('verdor_id', models.CharField(max_length=255, verbose_name='所属供应商ID')),
                ('verdor_name', models.CharField(max_length=255, verbose_name='所属供应商名字')),
                ('app_classify_id', models.CharField(max_length=255, verbose_name='应用分类ID')),
                ('app_classify_name', models.CharField(max_length=255, verbose_name='应用分类名字')),
                ('get_time', models.DateTimeField(auto_now_add=True, verbose_name='数据落地时间')),
            ],
            options={
                'verbose_name': '物联设备meta数据',
                'verbose_name_plural': '物联设备meta数据',
            },
        ),
    ]
