# Generated by Django 2.0.1 on 2018-06-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0006_getdata_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdata_v2',
            name='floor',
            field=models.IntegerField(verbose_name='安装楼层'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='point_id',
            field=models.IntegerField(verbose_name='关联事件ID'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='point_type',
            field=models.IntegerField(verbose_name='关联事件类型'),
        ),
    ]
