# Generated by Django 2.0.6 on 2018-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0008_arc_data_v2_charge_data_v2_dirty_data_v2_door_data_day_v2_door_data_month_v2_door_data_v2_door_data_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge_data_v2',
            name='inusePlugNumber',
            field=models.IntegerField(verbose_name='插头数量'),
        ),
        migrations.AlterField(
            model_name='charge_data_v2',
            name='plugNumber',
            field=models.IntegerField(verbose_name='充电口编号'),
        ),
    ]
