# Generated by Django 2.0.6 on 2018-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0009_auto_20180628_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdata_v2',
            name='floor',
            field=models.CharField(max_length=255, verbose_name='安装楼层'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='point_id',
            field=models.CharField(max_length=255, verbose_name='关联事件ID'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='point_type',
            field=models.CharField(max_length=255, verbose_name='关联事件类型'),
        ),
    ]
