# Generated by Django 2.0.6 on 2018-06-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0010_auto_20180628_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdata_v2',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='安装地址'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='app_classify_id',
            field=models.CharField(max_length=255, null=True, verbose_name='应用分类ID'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='app_classify_name',
            field=models.CharField(max_length=255, null=True, verbose_name='应用分类名字'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='build_time',
            field=models.CharField(max_length=255, null=True, verbose_name='安装时间'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='committee_id',
            field=models.CharField(max_length=255, null=True, verbose_name='所属居委ID'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='committee_name',
            field=models.CharField(max_length=255, null=True, verbose_name='所属居委名字'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='device_type',
            field=models.CharField(max_length=255, null=True, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='floor',
            field=models.CharField(max_length=255, null=True, verbose_name='安装楼层'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='get_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='数据落地时间'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='lat',
            field=models.CharField(max_length=255, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='lng',
            field=models.CharField(max_length=255, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='photo_url',
            field=models.CharField(max_length=255, null=True, verbose_name='现场照片URL'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='piece_id',
            field=models.CharField(max_length=255, null=True, verbose_name='所属片区ID'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='piece_name',
            field=models.CharField(max_length=255, null=True, verbose_name='所属片区名字'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='point_id',
            field=models.CharField(max_length=255, null=True, verbose_name='关联事件ID'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='point_name',
            field=models.CharField(max_length=255, null=True, verbose_name='关联事件名字'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='point_type',
            field=models.CharField(max_length=255, null=True, verbose_name='关联事件类型'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='point_type_name',
            field=models.CharField(max_length=255, null=True, verbose_name='关联事件类型名字'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='region_id',
            field=models.CharField(max_length=255, null=True, verbose_name='所属街道ID'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='region_name',
            field=models.CharField(max_length=255, null=True, verbose_name='所属街道名称'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='sensor_id',
            field=models.CharField(max_length=255, null=True, verbose_name='设备ID'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='sensor_name',
            field=models.CharField(max_length=255, null=True, verbose_name='设备名字'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='verdor_id',
            field=models.CharField(max_length=255, null=True, verbose_name='所属供应商ID'),
        ),
        migrations.AlterField(
            model_name='getdata_v2',
            name='verdor_name',
            field=models.CharField(max_length=255, null=True, verbose_name='所属供应商名字'),
        ),
    ]
