# Generated by Django 2.0.6 on 2018-06-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0011_auto_20180628_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='location_x',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='location_y',
            new_name='lng',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='area',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='e_id',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='street',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='village',
        ),
        migrations.AddField(
            model_name='equipment',
            name='build_time',
            field=models.CharField(max_length=255, null=True, verbose_name='安装时间'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='change_time',
            field=models.DateTimeField(auto_now=True, verbose_name='状态改变时间'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='committee_id',
            field=models.CharField(max_length=255, null=True, verbose_name='所属居委ID'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='committee_name',
            field=models.CharField(max_length=255, null=True, verbose_name='所属居委名字'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='floor',
            field=models.CharField(max_length=255, null=True, verbose_name='安装楼层'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='piece_id',
            field=models.CharField(max_length=255, null=True, verbose_name='所属片区ID'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='piece_name',
            field=models.CharField(max_length=255, null=True, verbose_name='所属片区名字'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='point_id',
            field=models.CharField(max_length=255, null=True, verbose_name='关联事件ID'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='point_name',
            field=models.CharField(max_length=255, null=True, verbose_name='关联事件名字'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='point_type',
            field=models.CharField(max_length=255, null=True, verbose_name='关联事件类型'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='point_type_name',
            field=models.CharField(max_length=255, null=True, verbose_name='关联事件类型名字'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='region_id',
            field=models.CharField(max_length=255, null=True, verbose_name='所属街道ID'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='region_name',
            field=models.CharField(max_length=255, null=True, verbose_name='所属街道名称'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sensor_id',
            field=models.CharField(max_length=50, null=True, verbose_name='设备标识ID'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sensor_name',
            field=models.CharField(max_length=200, null=True, verbose_name='设备名字'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='安装地址'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='water_app.Equipment_type', verbose_name='传感器类型'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.IntegerField(choices=[(7, '正常'), (4, '低电压'), (1, '报警'), (0, '未知')], default=0, verbose_name='传感器状态'),
        ),
    ]
