# Generated by Django 2.0.7 on 2018-07-31 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0012_auto_20180629_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Focus_data_v2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=255, null=True, verbose_name='设备ID')),
                ('meta_type', models.CharField(max_length=255, null=True, verbose_name='设备类型')),
                ('region_name', models.CharField(max_length=200, null=True, verbose_name='街道名字')),
                ('village_name', models.CharField(max_length=200, null=True, verbose_name='居委名字')),
                ('address_name', models.CharField(max_length=200, null=True, verbose_name='楼地址')),
                ('street_lat', models.CharField(default='', max_length=200, verbose_name='街道纬度')),
                ('street_lng', models.CharField(default='', max_length=200, verbose_name='街道经度')),
                ('village_lat', models.CharField(default='', max_length=200, verbose_name='居委会纬度')),
                ('village_lng', models.CharField(default='', max_length=200, verbose_name='居委会经度')),
                ('lat', models.CharField(max_length=100, null=True, verbose_name='楼纬度')),
                ('lng', models.CharField(max_length=100, null=True, verbose_name='楼经度')),
                ('floor', models.CharField(default='', max_length=255, null=True, verbose_name='安装楼层')),
                ('get_time', models.DateTimeField(auto_now_add=True, verbose_name='报警时间')),
            ],
            options={
                'verbose_name': '实时报警详情',
                'verbose_name_plural': '实时报警详情',
            },
        ),
        migrations.CreateModel(
            name='IsUpdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_update', models.BooleanField(default=False, verbose_name='大屏地图是否同步模拟的数据')),
            ],
            options={
                'verbose_name': '大屏地图是否刷新',
                'verbose_name_plural': '大屏地图是否刷新',
            },
        ),
        migrations.CreateModel(
            name='Log_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=255, null=True, verbose_name='类型')),
                ('log_address', models.CharField(max_length=255, null=True, verbose_name='报警救援名称')),
                ('log_status', models.CharField(max_length=255, null=True, verbose_name='状态')),
                ('get_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '日志月志周志',
                'verbose_name_plural': '日志月志周志',
            },
        ),
        migrations.CreateModel(
            name='Map_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='地址(楼)')),
                ('lat', models.CharField(max_length=100, null=True, verbose_name='纬度')),
                ('lng', models.CharField(max_length=100, null=True, verbose_name='经度')),
                ('committee_id', models.CharField(max_length=200, null=True, verbose_name='居委会名字')),
                ('region_id', models.CharField(max_length=200, null=True, verbose_name='街道名字')),
                ('count', models.IntegerField(default=0, verbose_name='楼总数量')),
                ('smoke_num', models.IntegerField(default=0, verbose_name='烟感类型数量')),
                ('water_num', models.IntegerField(default=0, verbose_name='水压类型数量')),
                ('door_num', models.IntegerField(default=0, verbose_name='门磁类型数量')),
                ('video_num', models.IntegerField(default=0, verbose_name='视频类型数量')),
                ('tr_num', models.IntegerField(default=0, verbose_name='垃圾满溢类型数量')),
                ('g_num', models.IntegerField(default=0, verbose_name='地磁类型数量')),
                ('x_num', models.IntegerField(default=0, verbose_name='红外类型数量')),
                ('ele_num', models.IntegerField(default=0, verbose_name='电弧灭弧类型数量')),
                ('face_num', models.IntegerField(default=0, verbose_name='人脸识别类型数量')),
                ('addg_num', models.IntegerField(default=0, verbose_name='充电桩类型数量')),
                ('lift_num', models.IntegerField(default=0, verbose_name='电梯类型数量')),
                ('ph_num', models.IntegerField(default=0, verbose_name='PH类型数量')),
                ('N_num', models.IntegerField(default=0, verbose_name='溶解氧类型数量')),
            ],
            options={
                'verbose_name': '楼解析数据',
                'verbose_name_plural': '楼解析数据',
            },
        ),
        migrations.CreateModel(
            name='Map_point_street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=200, null=True, verbose_name='街道名字')),
                ('lat', models.CharField(max_length=100, null=True, verbose_name='街道纬度')),
                ('lng', models.CharField(max_length=100, null=True, verbose_name='街道经度')),
                ('count', models.IntegerField(default=0, verbose_name='街道总数量')),
                ('smoke_num', models.IntegerField(default=0, verbose_name='烟感类型数量')),
                ('water_num', models.IntegerField(default=0, verbose_name='水压类型数量')),
                ('door_num', models.IntegerField(default=0, verbose_name='门磁类型数量')),
                ('video_num', models.IntegerField(default=0, verbose_name='视频类型数量')),
                ('tr_num', models.IntegerField(default=0, verbose_name='垃圾满溢类型数量')),
                ('g_num', models.IntegerField(default=0, verbose_name='地磁类型数量')),
                ('x_num', models.IntegerField(default=0, verbose_name='红外类型数量')),
                ('ele_num', models.IntegerField(default=0, verbose_name='电弧灭弧类型数量')),
                ('face_num', models.IntegerField(default=0, verbose_name='人脸识别类型数量')),
                ('addg_num', models.IntegerField(default=0, verbose_name='充电桩类型数量')),
                ('lift_num', models.IntegerField(default=0, verbose_name='电梯类型数量')),
                ('ph_num', models.IntegerField(default=0, verbose_name='PH类型数量')),
                ('N_num', models.IntegerField(default=0, verbose_name='溶解氧类型数量')),
            ],
            options={
                'verbose_name': '街道解析数据',
                'verbose_name_plural': '街道解析数据',
            },
        ),
        migrations.CreateModel(
            name='Map_point_type_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_type', models.CharField(max_length=255, null=True, verbose_name='设备类型')),
                ('region_name', models.CharField(max_length=200, null=True, verbose_name='街道名字')),
                ('village_name', models.CharField(max_length=200, null=True, verbose_name='居委名字')),
                ('address_name', models.CharField(max_length=200, null=True, verbose_name='楼地址')),
                ('lat', models.CharField(max_length=100, null=True, verbose_name='楼纬度')),
                ('lng', models.CharField(max_length=100, null=True, verbose_name='楼经度')),
                ('count', models.IntegerField(default=0, verbose_name='楼内类型数量')),
            ],
            options={
                'verbose_name': '楼内类型数量数据',
                'verbose_name_plural': '楼内类型数量数据',
            },
        ),
        migrations.CreateModel(
            name='Map_point_type_street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_type', models.CharField(max_length=255, null=True, verbose_name='设备类型')),
                ('region_name', models.CharField(max_length=200, null=True, verbose_name='街道名字')),
                ('lat', models.CharField(max_length=100, null=True, verbose_name='街道纬度')),
                ('lng', models.CharField(max_length=100, null=True, verbose_name='街道经度')),
                ('count', models.IntegerField(default=0, verbose_name='街道类型数量')),
            ],
            options={
                'verbose_name': '街道下类型数量数据',
                'verbose_name_plural': '街道下类型数量数据',
            },
        ),
        migrations.CreateModel(
            name='Map_point_type_village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_type', models.CharField(max_length=255, null=True, verbose_name='设备类型')),
                ('region_name', models.CharField(max_length=200, null=True, verbose_name='街道名字')),
                ('village_name', models.CharField(max_length=200, null=True, verbose_name='居委名字')),
                ('lat', models.CharField(max_length=100, null=True, verbose_name='居委纬度')),
                ('lng', models.CharField(max_length=100, null=True, verbose_name='居委经度')),
                ('count', models.IntegerField(default=0, verbose_name='居委类型数量')),
            ],
            options={
                'verbose_name': '居委下类型数量数据',
                'verbose_name_plural': '居委下类型数量数据',
            },
        ),
        migrations.CreateModel(
            name='Map_point_village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(max_length=200, null=True, verbose_name='居委会名字')),
                ('region_name', models.CharField(max_length=200, null=True, verbose_name='街道名字')),
                ('lat', models.CharField(max_length=100, null=True, verbose_name='居委纬度')),
                ('lng', models.CharField(max_length=100, null=True, verbose_name='居委经度')),
                ('count', models.IntegerField(default=0, verbose_name='居委总数量')),
                ('smoke_num', models.IntegerField(default=0, verbose_name='烟感类型数量')),
                ('water_num', models.IntegerField(default=0, verbose_name='水压类型数量')),
                ('door_num', models.IntegerField(default=0, verbose_name='门磁类型数量')),
                ('video_num', models.IntegerField(default=0, verbose_name='视频类型数量')),
                ('tr_num', models.IntegerField(default=0, verbose_name='垃圾满溢类型数量')),
                ('g_num', models.IntegerField(default=0, verbose_name='地磁类型数量')),
                ('x_num', models.IntegerField(default=0, verbose_name='红外类型数量')),
                ('ele_num', models.IntegerField(default=0, verbose_name='电弧灭弧类型数量')),
                ('face_num', models.IntegerField(default=0, verbose_name='人脸识别类型数量')),
                ('addg_num', models.IntegerField(default=0, verbose_name='充电桩类型数量')),
                ('lift_num', models.IntegerField(default=0, verbose_name='电梯类型数量')),
                ('ph_num', models.IntegerField(default=0, verbose_name='PH类型数量')),
                ('N_num', models.IntegerField(default=0, verbose_name='溶解氧类型数量')),
            ],
            options={
                'verbose_name': '居委解析数据',
                'verbose_name_plural': '居委解析数据',
            },
        ),
        migrations.CreateModel(
            name='Test_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.IntegerField(choices=[(1, '报警'), (7, '未报警')], default=1, verbose_name='是否报警')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_app.Getdata_v2', verbose_name='设备ID')),
            ],
            options={
                'verbose_name': '模拟报警',
                'verbose_name_plural': '模拟报警',
            },
        ),
        migrations.RemoveField(
            model_name='focus_data',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='focus_data',
            name='state',
        ),
        migrations.AddField(
            model_name='block',
            name='village_lat',
            field=models.CharField(default='', max_length=200, verbose_name='居委会纬度'),
        ),
        migrations.AddField(
            model_name='block',
            name='village_lng',
            field=models.CharField(default='', max_length=200, verbose_name='居委会经度'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.IntegerField(choices=[(7, '正常'), (4, '异常'), (1, '报警'), (0, '未知')], default=0, verbose_name='传感器状态'),
        ),
        migrations.AlterField(
            model_name='member',
            name='area',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='权限选项'),
        ),
    ]
